apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: medhistory-service-deployment
  labels:
    app: medhistory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medhistory-service
  template:
    metadata:
      labels:
        app: medhistory-service
    spec:
      containers:
      - name: medhistory-service
        image: docker.artifactory.surescripts.local/gaden/innovation-days/medhistoryservice:0.1